print("HELLO WORLD")
print(20*"-")
print("    CALCULATOR   ")
print(20*"-")
a = int(input("A="))
b = int(input("B="))
print(20*"-")
print("A+B=", a+b)
print("A-B=", a-b)
print("A*B=", a*b)
print("A/B=", a/b)
print(20*"-")
